spring.application.name=Netflix-1
spring.datasource.url=jdbc:mysql://localhost:3306/Netflixx
spring.datasource.username=root
spring.datasource.password=siddhi12072005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true